color:
  brandStrength: 0.1865226421505213
  saturation: 0.2067959278356284
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  lightness: 0.8000688797328621
  rhythmicContrast: 0.5916984097566456
analytics:
  facebook: null
  google: null
  twitter: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  version: null
  bucket: null
favicon: null
layout_spectrum: 0.1643388757947832
purpose: []
name: HDR Video
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2093888705130666
